# -*- coding: utf-8 -*-
"""Copy of Employee Data Preprocessing.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1F36k1h2zk3SIQP5QqRnlTIGYXV13Q8IE
"""

from google.colab import files
uploaded = files.upload()

import io 
import pandas as pd

df = pd.read_csv(io.BytesIO(uploaded['Employee_Income.csv']))
print (df)

df.head()

df.dtypes

df.describe

df.isnull().sum()

df.corr()

df['income'].value_counts()

df['income'] = [ 0 if x == 'c=50k' else 1 for x in df ['income']]

df ['income'].value_counts()